### ISSUE TITLE
GIT Push from AWX Issues

### ISSUE THREAD

**Issue by danielbostock** [lvrfrc87/git-acp-ansible#22]
Hi,

Apologies if I am making some mistakes in here upfront with regards to how I have written my playbook for Ansible AWX or I am simply not understanding something correctly from how AWX is meant to work.

I am currently hosting AWX in Docker and also GitLab, and they are on the same Docker host.

Also as an FYI, I don't have an issue running this playbook directly from my computer with Ansible, so I don't think it is entirely to do with this module but maybe how it works or how I think it should work with AWX.

I have written the following playbook. Also all the "git_..." vars are pulled from the "token.yml" vars file.

```yml
---

# AWX Backup

- name: Manual Backup of Network Devices
  hosts: nvlan_network_hosts_switch
  gather_facts: no
  become: yes
  vars:
    backupdir: netdevbkp/
    repo: https://localhost:2443/danielbostock/network_device_backups.git
  vars_files:
    - ./token.yml
  collections:
    - lvrfrc87.git_acp
  serial: 1

  tasks:

    - name: Backup of the current running config before deploying changes to the device
      ios_config:
        backup: yes
        backup_options:
          dir_path: "{{ backupdir }}"
          filename: "{{ inventory_hostname }}"

    - name: HTTPS | add Backup File.
      git_acp:
        user: "{{ git_user }}"
        token: "{{ git_token }}"
        user_name: "{{git_user}}"
        user_email: "{{ git_email }}"
        path: "{{ backupdir }}"
        branch: master
        comment: "{{inventory_hostname}} - backup completed"
        remote: origin
        add: [ "{{inventory_hostname}}" ]
        mode: https
        url: "{{ repo }}"
```

While the playbook is being executed by AWX, the first Cisco switch backs up fine and the file is stored in the netdevbkp/ folder. However when the git_acp module is executed it gets the following error.

```json
{
    "msg": "error: src refspec master does not match any.\nerror: failed to push some refs to 'file:///var/lib/awx/projects/_36__network_device_backup'\n",
    "invocation": {
        "module_args": {
            "path": "netdevbkp/",
            "branch": "master",
            "comment": "nvsw1 - backup completed",
            "add": [
                "nvsw1"
            ],
            "mode": "local",
            "url": "network_device_backups.git",
            "user_name": "omitted",
            "user_email": "omitted",
            "remote": "origin",
            "user": null,
            "token": null,
            "push_option": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}
```

I am not really sure how to understand that "msg:" error that AWX is providing. From what I am understanding that error means it doesn't have a branch to push to because most likely the repo doesn't exist. But maybe there is something I need to change here in how I write the playbook to work with AWX in terms of folder for the file and repo locations?

Thanks in advance for any and all help provided to get this sorted, also I will be clear I am an Ansible/AWX noob so I am probably missing something obvious here!

**Comment by lvrfrc87** [comment]
@danielbostock it might be that the module does not find `.git` under your working directory

Have a look to this https://github.com/lvrfrc87/git-acp-ansible/issues/11 and this https://github.com/lvrfrc87/git-acp-ansible/issues/16

You might try to change `path: "{{ backupdir }}"` into `path: "{{ playbook_dir }}/{{ backupdir }}"`

**Comment by lvrfrc87** [comment]
@danielbostock did you have any chance to test the above?

**Comment by danielbostock** [comment]
Hey @lvrfrc87,

Apologies for the delays in my reply. Thanks heaps for your help here with this.

I had a read of those two other issues, but wasn't really sure how to directly relate them to the issue I was facing other than the mention of the playbook_dir variable which to tbh I had no idea about so its been great learning about that var!

I have adjusted the playbook to include your suggestion. However I still encountered issues.

Error message with `"{{playbook_dir}}/{{ backupdir }}"`

```json
{
    "rc": 128,
    "msg": "fatal: pathspec 'nvsw1' did not match any files\n",
    "command": "git add -- nvsw1",
    "invocation": {
        "module_args": {
            "user": "danielbostock",
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "user_name": "username",
            "user_email": "username@emai.com",
            "path": "/tmp/awx_5558_3icosy76/project/awx/netdevbkp/",
            "branch": "master",
            "comment": "nvsw1 - backup completed",
            "remote": "origin",
            "add": [
                "nvsw1"
            ],
            "mode": "https",
            "url": "https://localhost:2443/danielbostock/network_device_backups.git",
            "push_option": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}
```

I then guessed the issue might be related to where the backup of the config was being saved to in the ios_config module. I have then updated the var in there include the playbook_dir var as well.

`dir_path: "{{playbook_dir}}/{{ backupdir }}"`

I then re-ran the playbook in awx and this is the result.

```json
{
    "msg": "error: src refspec master does not match any.\nerror: failed to push some refs to 'file:///var/lib/awx/projects/_36__network_device_backup'\n",
    "invocation": {
        "module_args": {
            "user": "danielbostock",
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "user_name": "username",
            "user_email": "username@email.com",
            "path": "/tmp/awx_5560_7zlg8oua/project/awx/netdevbkp/",
            "branch": "master",
            "comment": "nvsw1 - backup completed",
            "remote": "origin",
            "add": [
                "nvsw1"
            ],
            "mode": "https",
            "url": "https://localhost:2443/danielbostock/network_device_backups.git",
            "push_option": null
        }
    },
    "_ansible_no_log": false,
    "changed": false
}
```
I can provide more debug verbose information if that would be more helpful for you to understand the issue?

Thanks,
Daniel.

**Comment by lvrfrc87** [comment]
@danielbostock can you try for me to change `"add": [ "nvsw1" ]` into `add: [ "." ]` which is the default value

**Comment by lvrfrc87** [comment]
@danielbostock did you have any chance to test the above? Thanks!

**Comment by danielbostock** [comment]
Hey mate,

Apologies for effectively going AWOL.

So I have been trying a few things sporadically over the last few days to try and get it working. It primarily seems to be an issue with getting the git_acp module in awx to recognise the .git file. I wrote the playbook exactly as what you have suggested and modified it based on your latest suggestion. All these had the refspec issue (which means unable to find repo or .git file to push to).

I have therefore then provided in path the full path to the project folder as an alternative in my playbook. This has produced a somewhat helpful result but not a successful result. I suspect this is because of the temporary way in which a playbook is run as to why I am having this particular set of issues.

```yml

# AWX Backup

- name: AWX Backup of Network Devices
  hosts: nvlan_network_hosts_switch
  gather_facts: no
  become: yes
  vars:
    bkp_dir: netdevbkp
    git_repo: git@gitlab.localhost:2222/danielbostock/network_device_backups.git
    pro_dir: /var/lib/awx/projects/_36__network_device_backup/
  vars_files:
    - ./token.yml
  collections:
    - lvrfrc87.git_acp
  serial: 1

  tasks:

    - name: Backup of the current running config before deploying changes to the device
      ios_config:
        backup: yes
        backup_options:
          dir_path: "{{ pro_dir }}/{{ bkp_dir }}"
          filename: "{{ inventory_hostname }}"

    - name: SSH GIT Push with git_acp
      git_acp:
        path: "{{ pro_dir }}"
        branch: master
        comment: "{{ inventory_hostname }} - Backup Complete"
        add: [ "{{ pro_dir }}{{ bkp_dir }}/{{ inventory_hostname }}" ]
        remote: origin
        mode: ssh
        url: "{{ git_repo }}"
        user_name: "{{ git_user }}"
        user_email: "{{ git_email }}"

```

I get the following result in AWX log. I ran it with verbosity -vvvv , which I hope helps somewhat?

```json

Identity added: /tmp/awx_5807_jgwp15ny/artifacts/5807/ssh_key_data (daniel@danpc)
ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
SSH password: 
BECOME password[defaults to SSH password]: 
Vault password: 
host_list declined parsing /tmp/awx_5807_jgwp15ny/tmpus0n8ic6 as it did not pass its verify_file() method
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
Parsed /tmp/awx_5807_jgwp15ny/tmpus0n8ic6 inventory source with script plugin

PLAYBOOK: awx_netdevbkp.yml ****************************************************
1 plays in awx/awx_netdevbkp.yml
Read vars_file './token.yml'
Read vars_file './token.yml'
Read vars_file './token.yml'

PLAY [AWX Backup of Network Devices] *******************************************
META: ran handlers
Read vars_file './token.yml'

TASK [Backup of the current running config before deploying changes to the device] ***
task path: /tmp/awx_5807_jgwp15ny/project/awx/awx_netdevbkp.yml:21
<nvsw1.neverland.local> ESTABLISH LOCAL CONNECTION FOR USER: root
<nvsw1.neverland.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly `"&& mkdir "` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094053.185626-1008-174775858512322 `" && echo ansible-tmp-1605094053.185626-1008-174775858512322="` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094053.185626-1008-174775858512322 `" ) && sleep 0'
<nvsw1> Attempting python interpreter discovery
<nvsw1.neverland.local> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c '/var/lib/awx/venv/ansible/bin/python3.6 && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/ios/ios_config.py
<nvsw1.neverland.local> PUT /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/tmphsm6wzmu TO /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094053.185626-1008-174775858512322/AnsiballZ_ios_config.py
<nvsw1.neverland.local> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094053.185626-1008-174775858512322/ /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094053.185626-1008-174775858512322/AnsiballZ_ios_config.py && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c '/usr/libexec/platform-python /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094053.185626-1008-174775858512322/AnsiballZ_ios_config.py && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094053.185626-1008-174775858512322/ > /dev/null 2>&1 && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly `"&& mkdir "` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667 `" && echo ansible-tmp-1605094058.5348914-1008-46215548765667="` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/files/stat.py
<nvsw1.neverland.local> PUT /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/tmp9whvvy_8 TO /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/AnsiballZ_stat.py
<nvsw1.neverland.local> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/ /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/AnsiballZ_stat.py && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c '/usr/libexec/platform-python /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/AnsiballZ_stat.py && sleep 0'
<nvsw1.neverland.local> PUT /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/tmpdjuwz75k TO /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/source
<nvsw1.neverland.local> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/ /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/source && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/files/copy.py
<nvsw1.neverland.local> PUT /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/tmpz7jv_4g5 TO /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/AnsiballZ_copy.py
<nvsw1.neverland.local> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/ /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/AnsiballZ_copy.py && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c '/usr/libexec/platform-python /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/AnsiballZ_copy.py && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094058.5348914-1008-46215548765667/ > /dev/null 2>&1 && sleep 0'
changed: [nvsw1] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/libexec/platform-python"
    },
    "backup_path": "/var/lib/awx/projects/_36__network_device_backup//netdevbkp/nvsw1",
    "changed": true,
    "date": "2020-11-11",
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": true,
            "backup_options": {
                "dir_path": "/var/lib/awx/projects/_36__network_device_backup//netdevbkp",
                "filename": "nvsw1"
            },
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "host": null,
            "intended_config": null,
            "lines": null,
            "match": "line",
            "multiline_delimiter": "@",
            "parents": null,
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "running_config": null,
            "save_when": "never",
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "time": "11:27:40"
}
Read vars_file './token.yml'

TASK [SSH GIT Push with git_acp] ***********************************************
task path: /tmp/awx_5807_jgwp15ny/project/awx/awx_netdevbkp.yml:28
<nvsw1.neverland.local> ESTABLISH LOCAL CONNECTION FOR USER: root
<nvsw1.neverland.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly `"&& mkdir "` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094062.5207362-1057-141111173139720 `" && echo ansible-tmp-1605094062.5207362-1057-141111173139720="` echo /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094062.5207362-1057-141111173139720 `" ) && sleep 0'
Using module file /tmp/awx_5807_jgwp15ny/requirements_collections/ansible_collections/lvrfrc87/git_acp/plugins/modules/git_acp.py
<nvsw1.neverland.local> PUT /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/tmp83t_seba TO /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094062.5207362-1057-141111173139720/AnsiballZ_git_acp.py
<nvsw1.neverland.local> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094062.5207362-1057-141111173139720/ /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094062.5207362-1057-141111173139720/AnsiballZ_git_acp.py && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c '/usr/libexec/platform-python /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094062.5207362-1057-141111173139720/AnsiballZ_git_acp.py && sleep 0'
<nvsw1.neverland.local> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-local-998qcncrgly/ansible-tmp-1605094062.5207362-1057-141111173139720/ > /dev/null 2>&1 && sleep 0'
fatal: [nvsw1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "add": [
                "/var/lib/awx/projects/_36__network_device_backup/netdevbkp/nvsw1"
            ],
            "branch": "master",
            "comment": "nvsw1 - Backup Complete",
            "mode": "ssh",
            "path": "/var/lib/awx/projects/_36__network_device_backup/",
            "push_option": null,
            "remote": "origin",
            "token": null,
            "url": "git@gitlab.localhost:2222/danielbostock/network_device_backups.git",
            "user": null,
            "user_email": "hidden",
            "user_name": "hidden"
        }
    },
    "msg": "git@gitlab.localhost: Permission denied (publickey).\\r\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n"
}

PLAY RECAP *********************************************************************
nvsw1                      : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
