### ISSUE TITLE
https asking for username/password

### ISSUE THREAD

**Issue by tom0010** [lvrfrc87/git-acp-ansible#47]
I am trying to use `https` as auth method but when I run the playbook locally I get the prompt for my gitlab username and password, it seems the module is not recognising my username/token.

```yaml
  - name: "Checkout new branch"
    command:
      cmd: "git checkout -B {{ testvar }}"

  - name: "Create new file to upload"
    copy:
      src: mytest.txt
      dest: "{{ testvar }}.txt"

  - name: "Upload config files to gitlab"
    lvrfrc87.git_acp.git_acp:
      user: "myusername"
      token: "mytoken"
      path: "{{ playbook_dir }}"
      branch: "{{ testvar }}"
      add: ["{{ testvar }}.txt"]
      comment: '"{{ git_comment }}"'
      mode: https
      url: https://gitlab.mydomain.com/ansible/test-playbook.git
      user_name: "{{ awx_user_name }}"
      user_email: "{{ awx_user_email }}"
    vars:
      git_comment: "adding..."
      awx_user_name: "myusername"
      awx_user_email: "myname@myemail.com"

  - name: "Checkout back to master"
    command:
      cmd: "git checkout master"
``` 

Log:
```bash
TASK [Upload config files to gitlab] ************************************************************************************************************************************************************************
task path: /home/username/scripts/test-playbook/test2.yml:29
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: username
<localhost> EXEC /bin/sh -c 'echo ~username && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp `"&& mkdir "` echo /home/username/.ansible/tmp/ansible-tmp-1660210601.6489577-394703-105101875950356 `" && echo ansible-tmp-1660210601.6489577-394703-105101875950356="` echo /home/username/.ansible/tmp/ansible-tmp-1660210601.6489577-394703-105101875950356 `" ) && sleep 0'
Using module file /home/username/scripts/test-playbook/collections/ansible_collections/lvrfrc87/git_acp/plugins/modules/git_acp.py
<localhost> PUT /home/username/.ansible/tmp/ansible-local-394595usq90jg0/tmpglg58whh TO /home/username/.ansible/tmp/ansible-tmp-1660210601.6489577-394703-105101875950356/AnsiballZ_git_acp.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1660210601.6489577-394703-105101875950356/ /home/username/.ansible/tmp/ansible-tmp-1660210601.6489577-394703-105101875950356/AnsiballZ_git_acp.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/username/.ansible/tmp/ansible-tmp-1660210601.6489577-394703-105101875950356/AnsiballZ_git_acp.py && sleep 0'
Username for 'https://gitlab.mydomain.com': ^C [ERROR]: User interrupted execution.   <<<< here
```

In my `.git/config` I did have the ssh url which was using my local ssh key to push code, however, after swapping to `https` I get this error. 
Is it possible that the collection is just using my `.git/config` and disregarding my ansible config parameters?
