### ISSUE TITLE
Can we handle ssh key passphrasees somehow? 

### ISSUE THREAD

**Issue by tom0010** [lvrfrc87/git-acp-ansible#67]
As the title says, I guess. 
Looks like Ansible is failing when we use this, getting `rc` of 128.

**Comment by tom0010** [comment]
I ended up doing something like this:
```yaml
---
- name: "Load SSH key"
  shell: "eval \"$(ssh-agent)\" && ssh-add ~/.ssh/id_rsa && echo $SSH_AUTH_SOCK"
  register: "ssh_agent"

- name: "Test SSH key"
  command: "ssh-add -l"
  environment:
    SSH_AUTH_SOCK: "{{ ssh_agent.stdout_lines.1 }}"
```
The key thing is the `environment` part.
