### ISSUE TITLE
Fatal error when performing a git push where branch is up to date, but with untracked files present

### ISSUE THREAD

**Issue by djpbessems** [lvrfrc87/git-acp-ansible#70]
When executing the following task:
```
- name: Add/Commit/Push git repository
  lvrfrc87.git_acp.git_acp:
    path: "{{ git_repo.path }}"
    branch: main
    comment: "Upload files"
    add:
      - ./subfolder
    url: https://<fqdn>/repo.git
  environment:
    GIT_AUTHOR_NAME: foo
    GIT_AUTHOR_EMAIL: foo@bar.it
    GIT_COMMITTER_NAME: foo
    GIT_COMMITTER_EMAIL: foo@bar.it
```
I'm getting the following error:
```
TASK [Add/Commit/Push git repository] *****************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "command": "/usr/bin/git commit -m Upload manifests", "msg": "Error in running '/usr/bin/git commit -m Upload manifests' command", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "On branch main\nYour branch is up to date with 'origin/main'.\n\nUntracked files:\n  (use \"git add <file>...\" to include in what will be committed)\n\tfile1\n\tfile2\n\nnothing added to commit but untracked files present (use \"git add\" to track)\n", "stdout_lines": ["On branch main", "Your branch is up to date with 'origin/main'.", "", "Untracked files:", "  (use \"git add <file>...\" to include in what will be committed)", "\tfile1", "\tfile2", "", "nothing added to commit but untracked files present (use \"git add\" to track)"]}
```

Is there way to accept(/ignore) the untracked files (they are left for a future commit) and not error on them?
Or can I somehow make a conditional check with the regular `ansible.builtin.git` module to remove untracked files (I highly doubt it, because their attitude seems to be "no edge cases whatsoever" - see https://github.com/ansible/ansible/pull/39776#issuecomment-1137765667)?
