### ISSUE TITLE
Create a new branch when pushing new files

### ISSUE THREAD

**Issue by djpbessems** [lvrfrc87/git-acp-ansible#77]
When executing the following task:
```
- name: Add/Commit/Push git repository
  lvrfrc87.git_acp.git_acp:
    path: "{{ git_repo.path }}"
    branch: new-branch
    comment: "Upload files"
    add:
      - ./subfolder
    url: https://<fqdn>/repo.git
  environment:
    GIT_AUTHOR_NAME: foo
    GIT_AUTHOR_EMAIL: foo@bar.it
    GIT_COMMITTER_NAME: foo
    GIT_COMMITTER_EMAIL: foo@bar.it
```
I'm getting the following error:
```
TASK [Add/Commit/Push git repository] *****************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "command": "/usr/bin/git push ******** new-branch", "msg": "Error in running '/usr/bin/git push ******** new-branch' command", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "error: src refspec new-branch does not match any\nerror: failed to push some refs to 'https://<fqdn>/repo.git'\n", "stdout_lines": ["error: src refspec new-branch does not match any", "error: failed to push some refs to 'https://<fqdn>/repo.git'"]}
```

Is there any way to automatically create a new branch (both locally and on the remote)?

I'd want this functionality to automatically create refs for different versions of a gitops repository during initial bootstrapping and upgrading of an appliance.
